### ISSUE TITLE
Thank you for good reference

### ISSUE THREAD

**Issue by IT-HONGREAT** [Yiling-J/django-admin-select-search#2]
Hi

I have a problem to use your code.

It raise error about load replace method.
I use django 3.2.9. 

![image](https://user-images.githubusercontent.com/80932397/187116436-f449c6db-42db-4922-a8d8-1704dac32ff0.png)

Could you help me??

**Comment by Yiling-J** [comment]
@IT-HONGREAT fixed, can you pull latest code and try again?

**Comment by IT-HONGREAT** [comment]
@Yiling-J 
It works very well !! 
Thank you so much! 👍
